import OTHER_BUILDING_MAIN_ENTRANCE from "../assets/nodes/OTHER_BUILDING_MAIN_ENTRANCE.jpeg";
import ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE from "../assets/nodes/ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE.jpeg";
import MAIN_BUILDING_MAIN_ENTRANCE from "../assets/nodes/MAIN_BUILDING_MAIN_ENTRANCE.jpeg";
import STREETS_CARRERA_16_40A from "../assets/nodes/STREETS_CARRERA_16_40A.jpeg";

const images = {
  OTHER_BUILDING_MAIN_ENTRANCE: OTHER_BUILDING_MAIN_ENTRANCE,
  ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE: ADMINISTRATIVE_BUILDING_MAIN_ENTRANCE,
  MAIN_BUILDING_MAIN_ENTRANCE: MAIN_BUILDING_MAIN_ENTRANCE,
  STREETS_CARRERA_16_40A: STREETS_CARRERA_16_40A,
};

export default images;
